import { Button, ListGroup } from 'react-bootstrap'

import Head from 'next/head'
import Todo from '../components/todo/Todo'
import styles from '@/styles/todolist.module.scss'
import { useState, useEffect } from 'react'
import uniqid from 'uniqid';
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import toasts from '../components/toasts/index'

export default function Home() {
  const [list, setList] = useState([]);

  useEffect(() => {
    const data = JSON.parse(localStorage.getItem('todosList')) || [];
    setList(data);
  }, [])
  

  const handleAdd = () => {
    const value = prompt('Добавить заметку');
    const newTask = { id: uniqid(), value };
    const newList = [...list, newTask];
    localStorage.setItem('todosList', JSON.stringify(newList));
    setList(newList);
    toasts.add();
  }

  const renderTodos = () => {
    if (list.length === 0) {
      return '';
    }

    return (
      list.map((todo) => {
        return <Todo key={todo.id} id={todo.id} value={todo.value} list={list} setList={setList} toasts={toasts}></Todo>
      })
    )
  };

  return (
    <>
      <Head>
        <title>Заметки</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>
      <main className={styles.main}>
        <ListGroup className={styles.todoList}>
          <Button variant="secondary" className={styles.addButton} onClick={handleAdd}>Добавить заметку</Button>
          {renderTodos()}
        </ListGroup>
        <ToastContainer></ToastContainer>
      </main>
    </>
  )
}
